### PR TITLE
SRI - 815 Add verifier.sol for workstep circuits

### PR DESCRIPTION
**Pull request by biscuitdey**
# Description

This PR adds the verifier contracts for the workstep circuits.
The verifier contracts are generated while compiling the circuits using the script (plonk.sh).

We are using three separate verifier contracts for the 3 worksteps 
because the verification key values are hardcoded inside the contract. 
Using one verifier contract (where we pass the verification key as a function
param) is not possible as the contract uses assembly inside solidity contract 
and assembly does not accept local variables. Also, if we declare the values as
storage variables, then we would have to change the verifyFunction code it as 
there is different syntax to use storage variables.

## Related Issue

#815 

## How Has This Been Tested

Tests would be added in upcoming PRs.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Request to be added as a Code Owner/Maintainer

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I commit to abide by the Responsibilities of Code Owners/Maintainers.

### CODE REVIEW

**Comment by biscuitdey** [comment]
@Therecanbeonlyone1969 Do we need all three workstep circuit contracts? OR can we use only the workstep1 verifier contract to verify all three proofs (workstep1, workstep2 and workstep3)?

**Comment by ognjenkurtic** [comment]
> @Therecanbeonlyone1969 Do we need all three workstep circuit contracts? OR can we use only the workstep1 verifier contract to verify all three proofs (workstep1, workstep2 and workstep3)?

My understanding from the call is that we can use a single one, although not sure why would the command create one contract for each circuit. I see that they differ only in the first dozen const variables. Anyways, leaving to @Therecanbeonlyone1969 for review.

**Review by Therecanbeonlyone1969 — DISMISSED** [review]
LGTM ... are we doing 3 contracts because of the different verification keys by circuit? @biscuitdey

**Comment by biscuitdey** [comment]
> LGTM ... are we doing 3 contracts because of the different verification keys by circuit? @biscuitdey

@Therecanbeonlyone1969 Yes. The verification key values (Qm, Ql, etc.) are hardcoded in each of the verifier contract.

**Comment by biscuitdey** [comment]
@ognjenkurtic @Therecanbeonlyone1969  I created a single verifier contract that accepts verification key as a param. Please re-approve PR.

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM. As an improvement, next time, let's update the verifier code to take storage variables

**Pull request merged**
